const navbarStyles = {
  navbar: {
    backgroundColor: "#ffffff",
    padding: "0.75rem 2rem",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
    position: "sticky",
    top: 0,
    zIndex: 1100,
  },
  toolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "2rem",
  },
  logo: {
    fontWeight: "bold",
    color: "#1976d2",
    cursor: "pointer",
    fontSize: "1.5rem",
    userSelect: "none",
  },
  navLinks: {
    display: "flex",
    gap: "1rem",
    flexGrow: 1,
    justifyContent: "center",
  },
  navButton: {
    color: "#555",
    fontWeight: 500,
    textTransform: "none",
    fontSize: "1rem",
    borderRadius: "6px",
    padding: "0.4rem 1rem",
    transition: "background-color 0.3s ease",
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
  },
  authButtons: {
    display: "flex",
    gap: "0.75rem",
  },
  loginButton: {
    color: "#1976d2",
    border: "2px solid #1976d2",
    backgroundColor: "transparent",
    fontWeight: "bold",
    padding: "0.4rem 1rem",
    borderRadius: "6px",
    textTransform: "none",
    transition: "background-color 0.3s ease",
    cursor: "pointer",
  },
  signupButton: {
    backgroundColor: "#1976d2",
    color: "#fff",
    fontWeight: "bold",
    borderRadius: "6px",
    padding: "0.4rem 1rem",
    textTransform: "none",
    transition: "background-color 0.3s ease",
    border: "none",
    cursor: "pointer",
  },
};

export default navbarStyles;
